// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace IGILab1Norm.Migrations
{
    [DbContext(typeof(RentContext))]
    partial class RentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IGILab1.Car", b =>
                {
                    b.Property<int>("CarID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BodyNum");

                    b.Property<int>("CarAge");

                    b.Property<string>("CarMark");

                    b.Property<int>("CarPrice");

                    b.Property<DateTime>("DateTO");

                    b.Property<int>("DayPrice");

                    b.Property<string>("EngNum");

                    b.Property<string>("MechFIO");

                    b.Property<int>("Mileage");

                    b.Property<string>("RegNum");

                    b.HasKey("CarID");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("IGILab1.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Adres");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("ClienFIO");

                    b.Property<string>("ClientSex");

                    b.Property<string>("PassNum");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("IGILab1.Rent", b =>
                {
                    b.Property<int>("RentID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CarID");

                    b.Property<int>("ClientID");

                    b.Property<DateTime>("DateGet");

                    b.Property<bool>("Paid");

                    b.Property<DateTime>("RentDate");

                    b.Property<int>("RentPrice");

                    b.Property<string>("WorkerFIO");

                    b.HasKey("RentID");

                    b.HasIndex("CarID");

                    b.HasIndex("ClientID");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("IGILab1.Rent", b =>
                {
                    b.HasOne("IGILab1.Car")
                        .WithMany("Rents")
                        .HasForeignKey("CarID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IGILab1.Client")
                        .WithMany("Rents")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
